# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0183f5672a81074923f189d3f81c4b221346c569aa7e6190f1dc4c1e25aa044359564dabe14174a8c3b10fc6c52262cf5e8cd3ab479025cd1ede32ece83a764

test:
  secret_key_base: 6f47156e515e107a48754694d209678e7930194075face237b9835f2fa4b946294f1f418be820e60bf7f2adf905e9254246cefaead30ade1f58f25f674082571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
